"use client"

import { ChipSingleSelect } from "@/sections/become-a-partner/form/ChipSingleSelect"
import { TextAreaField } from "@/sections/become-a-partner/form/TextAreaField"
import {
  REVENUE_RANGE_OPTIONS, ELIGIBILITY_CONFIDENCE_OPTIONS, PRIMARY_REASON_OPTIONS,
} from "@/sections/become-a-partner/data"
import type { PartnerApplicationState } from "@/sections/become-a-partner/form/formState"

interface Props {
  state: PartnerApplicationState
  set: <K extends keyof PartnerApplicationState>(key: K, value: PartnerApplicationState[K]) => void
}

export function FormStep3Commercial({ state, set }: Props) {
  return (
    <div className="flex flex-col gap-6">
      <h3 className="text-base font-bold text-text-primary">Commercial / Quality Information</h3>

      <ChipSingleSelect
        label="Estimated combined monthly revenue generated by the publishers you currently work with"
        required
        options={REVENUE_RANGE_OPTIONS}
        value={state.revenueRange}
        onChange={(v) => set("revenueRange", v)}
      />

      <ChipSingleSelect
        label="Do your publishers generally meet Click-Dudes eligibility requirements?"
        required
        options={ELIGIBILITY_CONFIDENCE_OPTIONS}
        value={state.eligibilityConfidence}
        onChange={(v) => set("eligibilityConfidence", v)}
      />

      <ChipSingleSelect
        label="Primary reason for partnering with Click-Dudes"
        required
        options={PRIMARY_REASON_OPTIONS}
        value={state.primaryReason}
        onChange={(v) => set("primaryReason", v)}
      />

      <TextAreaField
        id="pa-notes"
        label="Tell us briefly about your publisher network"
        optional
        placeholder="Property types, traffic sources, monetization history…"
        value={state.notes}
        onChange={(v) => set("notes", v)}
      />
    </div>
  )
}
