import type { LegalSectionData } from "@/lib/legal/types"

export const PRIVACY_SECTIONS: LegalSectionData[] = [
  {
    id: "introduction", number: 1, title: "Introduction",
    body: [
      "This Privacy Policy explains how Click Dudes, Inc. (\"Click Dudes,\" \"we,\" \"us\") collects, uses and shares information in connection with our public website, our publisher and partner services, and the Partner Portal at partners.clickdudes.com.",
      "By using our website or services, you acknowledge the practices described here.",
    ],
  },
  {
    id: "who-we-are", number: 2, title: "Who We Are",
    body: [
      "Click Dudes is a monetization, advertising-technology and partnership platform that helps web, app and CTV publishers grow revenue, and helps agencies, professionals and individuals refer qualified publisher opportunities into our partner network.",
    ],
  },
  {
    id: "scope", number: 3, title: "Scope of This Policy",
    body: [
      "This Policy covers clickdudes.com and the Partner Portal. It does not cover third-party websites or platforms we link to, or the monetization technologies our upstream partners operate directly on publisher properties, which are governed by those parties' own policies.",
    ],
  },
  {
    id: "information-we-collect", number: 4, title: "Information We Collect",
    body: [
      "We collect information in three broad ways: information you provide directly, information generated by your use of our Partner Portal, and technical information collected automatically when you visit our Sites.",
    ],
  },
  {
    id: "information-direct", number: 5, title: "Information Provided Directly",
    body: [
      "This includes your name, email address, phone or WhatsApp number, company name, and any other details you submit through contact forms, the revenue calculator, or general inquiries.",
    ],
  },
  {
    id: "publisher-partner-application", number: 6, title: "Publisher / Partner Application Information",
    body: [
      "When you apply to become a Click Dudes partner or submit a publisher opportunity, we collect information such as your partner type, publisher property details, estimated traffic and revenue ranges, and the publisher types you work with, so we can evaluate the application.",
      "We do not require or knowingly collect confidential upstream financial data belonging to third parties as part of this process.",
    ],
  },
  {
    id: "partner-portal-information", number: 7, title: "Partner Portal Information",
    body: [
      "If your application is approved and you are granted access to the Partner Portal, we process account information, submitted publisher records, review and approval status, commission and payment records, agreements, and support or chat communications, in order to operate the portal for you.",
    ],
  },
  {
    id: "website-device-information", number: 8, title: "Website and Device Information",
    body: [
      "When you visit our public website, we and our service providers may automatically collect technical information such as IP address, browser type, device type, referring page, and pages visited, generally in aggregate or pseudonymous form.",
    ],
  },
  {
    id: "cookies", number: 9, title: "Cookies and Similar Technologies",
    body: [
      "We use cookies and similar technologies as described in our Cookie Policy, including essential cookies for authentication and security, and, where enabled, analytics cookies to understand aggregate site usage.",
    ],
  },
  {
    id: "how-we-use", number: 10, title: "How We Use Information",
    body: [
      "We use the information described above to operate our website and Partner Portal, evaluate and manage partner applications, administer publisher submissions and referral commissions, respond to inquiries, maintain security, and meet legal obligations.",
    ],
  },
  {
    id: "publisher-partner-administration", number: 11, title: "Publisher and Partner Administration",
    body: [
      "We use application and portal information to review publisher eligibility, track submissions through onboarding, calculate eligible referral commissions under your approved partner agreement, and manage payments and agreements.",
    ],
  },
  {
    id: "communications", number: 12, title: "Communications",
    body: [
      "We use contact information to respond to inquiries, send account and transactional notices (such as status updates on a submitted publisher), and, where you have opted in, share partner program updates.",
    ],
  },
  {
    id: "service-improvement-security", number: 13, title: "Service Improvement and Security",
    body: [
      "We use technical and usage information to maintain, secure, troubleshoot and improve our website and Partner Portal, including detecting and preventing fraud, abuse, or unauthorized access.",
    ],
  },
  {
    id: "legal-compliance-uses", number: 14, title: "Legal / Compliance Uses",
    body: [
      "We may use and retain information as needed to comply with applicable law, respond to lawful requests from public authorities, enforce our Terms of Service, and protect the rights, property or safety of Click Dudes, our partners, or others.",
    ],
  },
  {
    id: "how-shared", number: 15, title: "How Information May Be Shared",
    body: [
      "We do not sell personal information. We may share information with the categories of recipients described in the following sections, and only as reasonably necessary for the purposes described in this Policy.",
    ],
  },
  {
    id: "service-providers", number: 16, title: "Service Providers",
    body: [
      "We use third-party service providers to help operate our Sites and services — for example, hosting, email delivery, and analytics providers — who process information on our behalf under appropriate confidentiality and data-handling terms.",
    ],
  },
  {
    id: "monetization-technology-partners", number: 17, title: "Monetization / Technology Partners",
    body: [
      "Where a publisher opportunity you submit is matched to an appropriate monetization-partner route, limited necessary information about the publisher property (not your personal financial information) may be shared with that upstream partner to evaluate and onboard the opportunity, consistent with our partner agreements.",
      "We do not share confidential upstream partner financial or calculation data with publishers or referral partners.",
    ],
  },
  {
    id: "google-advertising-technology", number: 18, title: "Google / Advertising Technology",
    body: [
      "Where our website uses Google Analytics, Google processes certain technical and usage data under its own privacy terms. Google Ad Manager and Google AdX are monetization technologies we help publisher partners implement on their own properties; those technologies do not run on clickdudes.com itself.",
    ],
  },
  {
    id: "business-transfers", number: 19, title: "Business Transfers",
    body: [
      "If Click Dudes is involved in a merger, acquisition, financing, or sale of assets, information may be transferred as part of that transaction, subject to the commitments described in this Policy.",
    ],
  },
  {
    id: "legal-requests", number: 20, title: "Legal Requests",
    body: [
      "We may disclose information if required to do so by law or in the good-faith belief that such action is necessary to comply with legal process or protect the rights, property or safety of Click Dudes, our users, or the public.",
    ],
  },
  {
    id: "international-processing", number: 21, title: "International Data Processing",
    body: [
      "Click Dudes and our service providers may process information in countries other than your own. Where we transfer personal information internationally, we take reasonable steps to apply appropriate safeguards consistent with applicable law.",
    ],
  },
  {
    id: "data-retention", number: 22, title: "Data Retention",
    body: [
      "We retain information for as long as reasonably necessary to fulfil the purposes described in this Policy — including for as long as your partner or publisher relationship is active — and thereafter for as long as needed to meet legal, accounting, dispute-resolution or agreement-enforcement obligations.",
    ],
  },
  {
    id: "security", number: 23, title: "Security",
    body: [
      "We use reasonable administrative, technical and organizational measures designed to protect information against unauthorized access, loss or misuse. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
    ],
  },
  {
    id: "privacy-choices", number: 24, title: "Your Privacy Choices",
    body: [
      "Depending on your location, you may have rights to access, correct, or request deletion of your personal information, or to object to or restrict certain processing. Where applicable law grants these rights, we will honor validated requests consistent with that law.",
    ],
  },
  {
    id: "access-correction-deletion", number: 25, title: "Access / Correction / Deletion Requests",
    body: [
      "To make a request regarding your personal information, contact us at contact@clickdudes.com. We may need to verify your identity before actioning a request, and some information may be retained where we have a legitimate business or legal reason to do so.",
    ],
  },
  {
    id: "marketing-choices", number: 26, title: "Marketing Communication Choices",
    body: [
      "Partner program marketing updates are only sent to applicants who separately opt in during the application process. You can unsubscribe from marketing communications at any time using the link provided in the message or by emailing contact@clickdudes.com.",
    ],
  },
  {
    id: "cookies-section", number: 27, title: "Cookies",
    body: [
      "For full detail on the specific cookies and similar technologies we use, see our Cookie Policy.",
    ],
  },
  {
    id: "third-party-links", number: 28, title: "Third-Party Links",
    body: [
      "Our Sites may link to third-party websites, including partner and monetization-technology providers. We are not responsible for the privacy practices of third-party sites, and we encourage you to review their own privacy policies.",
    ],
  },
  {
    id: "childrens-privacy", number: 29, title: "Children's Privacy",
    body: [
      "Our services are intended for business use by professionals, agencies, companies and qualified individuals, and are not directed at children. We do not knowingly collect personal information from children.",
    ],
  },
  {
    id: "updates", number: 30, title: "Updates to This Policy",
    body: [
      "We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. Material changes will be reflected in the \"Last Updated\" date at the top of this page.",
    ],
  },
  {
    id: "contact", number: 31, title: "Contact",
    body: [
      "Questions about this Privacy Policy or our data practices can be sent to contact@clickdudes.com, or by post to Click Dudes, Inc., 86-90 Paul Street, London, EC2A 4NE, United Kingdom.",
    ],
  },
]
